# Here I covered some of the most fundamental concepts of tensors using TensorFlow

More specifically:
* Intro to tensors
* Getting info about tensors
* Manipulating tensors
* Tensors & NumPy
* Using `@tf.function` (a way to speed up regular Python functions)
* using GPUs with TensorFlow
* Some Exercises

# Intro to tensors

## Using tf.constant() 

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the ndims of a tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the ndims of a vector
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[1, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check the ndims of a matrix
matrix.ndim

2

In [8]:
# Create another matrix
matrix1 = tf.constant([[10., 7.], 
                        [3., 2.],
                        [8., 9.]], dtype=tf.float16) # Specifying dtype
matrix1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# Check the ndims of a matrix1
matrix1.ndim

2

In [10]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# Check the ndims of tensor
tensor.ndim

3

## Using `tf.Variable()` 

In [12]:
# Create same tensor with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Changing elements in changeable tensors
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# Changing elements in unchangeable tensors (Not Possible)
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating Random tensors