# Practice assignments

### 1. How to create a boolean array?

In [1]:
import numpy as np

In [2]:
actual_array = [1, 0.8, 0, np.nan, 'i', "Hello", True, False]
bool_arr = np.array(actual_array, dtype=bool)
print("Actual Array: ", actual_array)
print("Boolean Array: ", bool_arr)

Actual Array:  [1, 0.8, 0, nan, 'i', 'Hello', True, False]
Boolean Array:  [ True  True False  True  True  True  True False]


### 2. Create a 3×3 numpy array of all True’s

In [3]:
np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 3. Replace all odd numbers in arr with -1  -> Input([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Input array: ", input)
input[input % 2 != 0] = -1
print("Input array after modification: ", input)

Input array:  [0 1 2 3 4 5 6 7 8 9]
Input array after modification:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 4. Convert a 1D array to a 2D array with 2 rows  -> Input: np.arange(10)

In [11]:
input = np.arange(10)
print("Input 1-D array: ", input)
output = np.reshape(input, (-1, 2))
print("Output 2-D array: \n", output)

Input 1-D array:  [0 1 2 3 4 5 6 7 8 9]
Output 2-D array: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### 5. Stack the arrays a and b horizontally.
   - Input
       - a = np.arange(10).reshape(2,-1)
       - b = np.repeat(1,10).reshape(2,-1)
   - Desired OUTPUT
       - array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
               [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [14]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print("a: \n", a, "\nb: \n", b)

a: 
 [[0 1 2 3 4]
 [5 6 7 8 9]] 
b: 
 [[1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
np.hstack((a, b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 6. Get the common items between a and b
   - Input:
       - a = np.array([1,2,3,2,3,4,3,4,5,6])
       - b = np.array([7,2,10,2,7,4,9,4,9,8])
    

   - Desired Output:    
       - array([2, 4])

In [19]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("a: \n", a, "\nb: \n", b)

a: 
 [1 2 3 2 3 4 3 4 5 6] 
b: 
 [ 7  2 10  2  7  4  9  4  9  8]


In [22]:
if (set(a) & set(b)):
    print("The common elements between a & b: \n", np.array(set(a) & set(b)))
else:
    print("No common elements between a & b")

The common elements between a & b: 
 {2, 4}
