# Assignment 2

### 1. Program to create a vector in Python

In [1]:
import numpy as np

In [6]:
vector_h = np.array([1., 2., 3., 4., 5.])
vector_v = np.array([[1.],
                     [2.],
                     [3.],
                     [4.],
                     [5.]])

print("Horizontal Vector: ", vector_h)
print("Vertical Vector: \n", vector_v)
print("The data types are: {}, {}".format(type(vector_h), type(vector_v)))

Horizontal Vector:  [1. 2. 3. 4. 5.]
Vertical Vector: 
 [[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
The data types are: <class 'numpy.ndarray'>, <class 'numpy.ndarray'>


### 2. Program to add two vectors

In [7]:
a = np.array([1, 2, 3])
print("The Vector A is: ", a)
b = np.array([2, 3, 4])
print("The Vector B is: ", b)
c = a + b
print("The Addition of Vector A and B is: ", c)

The Vector A is:  [1 2 3]
The Vector B is:  [2 3 4]
The Addition of Vector A and B is:  [3 5 7]


### 3. Program to multiply two vectors

In [8]:
a = np.array([1, 2, 3])
print("The Vector A is: ", a)
b = np.array([2, 3, 4])
print("The Vector B is: ", b)
c = a * b
print("The Multiplication of Vector A and B is: ", c)

The Vector A is:  [1 2 3]
The Vector B is:  [2 3 4]
The Multiplication of Vector A and B is:  [ 2  6 12]


### 4. Program to find Dot Product of two vectors

In [11]:
a = np.array([1, 2, 3])
print("The Vector A is: ", a)
b = np.array([2, 3, 4])
print("The Vector B is: ", b)
c = a @ b
print("The Dot Product of Vector A and B is: ", c)

The Vector A is:  [1 2 3]
The Vector B is:  [2 3 4]
The Dot Product of Vector A and B is:  20


### 5. Program to multiply scalars with vectors

In [12]:
a = np.array([1, 2, 3])
print("The Vector A is: ", a)
b = 5
print("The Scalar is: ", b)
c = b * a
print("The Multiplication of a scalar with Vector A is: ", c)

The Vector A is:  [1 2 3]
The Scalar is:  5
The Multiplication of a scalar with Vector A is:  [ 5 10 15]


### 6. Program to transpose a matrix

In [18]:
m = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print("The Matrix is: \n", m)
print("The Transpose of the Matrix is: \n", m.T)

The Matrix is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The Transpose of the Matrix is: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


### 7. Program to find the trace of a matrix

In [19]:
print("The Matrix is: \n", m)
print("The Trace of the Matrix is: \n", m.trace())

The Matrix is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The Trace of the Matrix is: 
 15


### 8. Program to flatten a matrix

In [20]:
print("The Matrix is: \n", m)
print("The Flattened Matrix is: \n", m.flatten())

The Matrix is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The Flattened Matrix is: 
 [1 2 3 4 5 6 7 8 9]


### 9. Program to find the rank of a matrix

In [21]:
print("The Matrix is: \n", m)
print("The Rank of the Matrix is: \n", np.linalg.matrix_rank(m))

The Matrix is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The Rank of the Matrix is: 
 2


### 10. Program for finding out Determinant of a Matrix

In [23]:
print("The Matrix is: \n", m)
print("The Determinant of the Matrix is: \n", np.linalg.det(m))

The Matrix is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The Determinant of the Matrix is: 
 0.0


### 11. Program for finding out eigen values and eigen vectors of a given matrix

In [26]:
print("The Matrix is: \n", m)
print("The Eigenvalues and Eigenvectors of the Matrix are:\n", np.linalg.eig(m))

The Matrix is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The Eigenvalues and Eigenvectors of the Matrix are:
 (array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


### 12. Program for finding out inverse of a matrix

In [29]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print("The Non-Singular Matrix is: \n", A)
print("The Inverse of the Matrix is: \n", np.linalg.inv(A))

The Non-Singular Matrix is: 
 [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
The Inverse of the Matrix is: 
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


### 13. Program for finding oul L1, L2 and Infinity norm of a given vector

In [33]:
a = np.array([1, 2, 3])
print("The Vector A is: \n", a)

print("The L1 Norm of the Vector A is: ", np.linalg.norm(a, 1))
print("The L2 Norm of the Vector A is: ", np.linalg.norm(a))
print("The Infinity Norm of the Vector A is: ", np.linalg.norm(a, np.inf))

The Vector A is: 
 [1 2 3]
The L1 Norm of the Vector A is:  6.0
The L2 Norm of the Vector A is:  3.7416573867739413
The Infinity Norm of the Vector A is:  3.0
